import { StyleSheet, Text, View } from 'react-native';
import Svg, { Defs, LinearGradient as SvgGradient, Path, Stop } from 'react-native-svg';
import { Screen } from '@/src/components/Screen';
import { colors } from '@/src/theme';

const week = [62, 78, 55, 88, 74, 92, 75];
const heat = [1,2,3,2,3,3,1,0,2,3,3,2,1,3,2,3,3,3,2,1,0,2,3,2,3,3,1,2];
const cats = [['Тело',82],['Работа',74],['Дисциплина',68],['Развитие',61]] as const;

export default function Stats(){return <Screen>
  <Text style={s.eye}>ТВОЯ ДИНАМИКА</Text><Text style={s.title}>Статистика</Text>
  <View style={s.switch}><Text style={[s.switchText,s.active]}>7 дней</Text><Text style={s.switchText}>30 дней</Text><Text style={s.switchText}>Год</Text></View>
  <View style={s.hero}><View><Text style={s.label}>СРЕДНЯЯ ЭФФЕКТИВНОСТЬ</Text><Text style={s.big}>75<Text style={s.green}>%</Text></Text><Text style={s.up}>↗  +8% к прошлой неделе</Text></View><View style={s.badge}><Text style={s.badgeN}>7</Text><Text style={s.badgeT}>дней серии</Text></View></View>

  <Text style={s.section}>ПРОГРЕСС НЕДЕЛИ</Text><View style={s.card}>
    <View style={s.chartWrap}><Svg width="100%" height="145" viewBox="0 0 340 145"><Defs><SvgGradient id="g" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor={colors.green} stopOpacity=".26"/><Stop offset="1" stopColor={colors.green} stopOpacity="0"/></SvgGradient></Defs><Path d="M5 103 C35 93 42 65 58 70 S92 105 110 93 S140 45 160 55 S196 82 214 72 S250 27 270 39 S307 62 335 55 L335 140 L5 140 Z" fill="url(#g)"/><Path d="M5 103 C35 93 42 65 58 70 S92 105 110 93 S140 45 160 55 S196 82 214 72 S250 27 270 39 S307 62 335 55" fill="none" stroke={colors.green} strokeWidth="4" strokeLinecap="round"/></Svg></View>
    <View style={s.days}>{['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'].map((d,i)=><View key={d} style={s.day}><Text style={s.dayN}>{week[i]}%</Text><Text style={s.dayL}>{d}</Text></View>)}</View>
  </View>

  <View style={s.two}><Metric value="525" unit="XP" label="заработано"/><Metric value="21" unit="/ 28" label="действий"/></View>
  <Text style={s.section}>АКТИВНОСТЬ</Text><View style={s.card}><Text style={s.cardTitle}>Последние 4 недели</Text><View style={s.heat}>{heat.map((v,i)=><View key={i} style={[s.cell,v===0?s.c0:v===1?s.c1:v===2?s.c2:s.c3]}/>)}</View><View style={s.legend}><Text style={s.small}>Меньше</Text>{[s.c0,s.c1,s.c2,s.c3].map((x,i)=><View key={i} style={[s.legendCell,x]}/>)}<Text style={s.small}>Больше</Text></View></View>

  <Text style={s.section}>БАЛАНС КАТЕГОРИЙ</Text><View style={s.card}>{cats.map(([name,val])=><View key={name} style={s.cat}><View style={s.catTop}><Text style={s.catName}>{name}</Text><Text style={s.catVal}>{val}%</Text></View><View style={s.track}><View style={[s.fill,{width:`${val}%`}]}/></View></View>)}</View>
  <Text style={s.section}>INSIGHT</Text><View style={[s.card,s.insight]}><Text style={s.spark}>✦</Text><View style={{flex:1}}><Text style={s.insightTitle}>Сильнее всего ты идёшь в субботу</Text><Text style={s.insightText}>Средний результат — 92%. Самая заметная зона роста сейчас — развитие: добавь одно небольшое действие в эту категорию.</Text></View></View>
</Screen>}
function Metric({value,unit,label}:{value:string;unit:string;label:string}){return <View style={[s.card,s.metric]}><Text style={s.metricN}>{value} <Text style={s.metricUnit}>{unit}</Text></Text><Text style={s.small}>{label}</Text></View>}
const s=StyleSheet.create({eye:{color:colors.green,fontSize:11,fontWeight:'900',letterSpacing:2,marginTop:8},title:{color:colors.text,fontSize:34,fontWeight:'900',marginTop:6},switch:{flexDirection:'row',backgroundColor:'#0B100D',borderRadius:16,padding:4,marginTop:20,borderWidth:1,borderColor:colors.line},switchText:{flex:1,textAlign:'center',color:colors.muted,paddingVertical:9,fontSize:11,fontWeight:'800'},active:{backgroundColor:'#172319',color:colors.green,borderRadius:12},hero:{marginTop:12,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:24,padding:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.2},big:{color:colors.text,fontSize:48,fontWeight:'900',marginTop:4},green:{color:colors.green},up:{color:colors.green,fontSize:10,fontWeight:'800'},badge:{width:88,height:88,borderRadius:44,borderWidth:7,borderColor:colors.green,alignItems:'center',justifyContent:'center'},badgeN:{color:colors.text,fontSize:25,fontWeight:'900'},badgeT:{color:colors.muted,fontSize:8,fontWeight:'700'},section:{color:colors.text,fontSize:12,fontWeight:'900',letterSpacing:1.5,marginTop:26,marginBottom:10},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:22,padding:17},chartWrap:{height:145,marginHorizontal:-6},days:{flexDirection:'row',justifyContent:'space-between'},day:{alignItems:'center'},dayN:{color:colors.text,fontSize:9,fontWeight:'800'},dayL:{color:colors.muted,fontSize:9,fontWeight:'800',marginTop:5},two:{flexDirection:'row',gap:10,marginTop:10},metric:{flex:1},metricN:{color:colors.text,fontSize:23,fontWeight:'900'},metricUnit:{color:colors.green,fontSize:11},small:{color:colors.muted,fontSize:10,marginTop:3},cardTitle:{color:colors.text,fontWeight:'800',fontSize:13},heat:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:15},cell:{width:'11%',aspectRatio:1,borderRadius:5},c0:{backgroundColor:'#121914'},c1:{backgroundColor:'#203A20'},c2:{backgroundColor:'#417A22'},c3:{backgroundColor:colors.green},legend:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:5,marginTop:10},legendCell:{width:10,height:10,borderRadius:3},cat:{marginBottom:17},catTop:{flexDirection:'row',justifyContent:'space-between'},catName:{color:colors.text,fontSize:12,fontWeight:'800'},catVal:{color:colors.green,fontSize:11,fontWeight:'900'},track:{height:6,backgroundColor:'#182019',borderRadius:99,overflow:'hidden',marginTop:8},fill:{height:'100%',backgroundColor:colors.green,borderRadius:99},insight:{flexDirection:'row',gap:13,alignItems:'flex-start'},spark:{color:colors.green,fontSize:22},insightTitle:{color:colors.text,fontSize:14,fontWeight:'900'},insightText:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:6}});
